### ISSUE TITLE
Request for comments: Option flags/settings for creating arrays and volumes

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#106]
Hey guys,

First, I have a new requirement. The same user that wants the read/write cache control also would need specific control over some options for creating volumes and arrays on Smart Array. For example, they create volumes on SSDs, but want to continue to use the controller BBWC with those SSDs (it just makes sense for their IO pattern). So, the command line option using hpssacli would look something like this for their requirement:

hpssacli ctrl slot=0 create type=ld drives=1i:1:13 size=max raid=0 ss=64 aa=enable

That "aa=enable" chunk is the only part missing in libstoragemgmt today. Now, I could go and create a command in libstoragemgmt called lsm_volume_raid_create_with_aa, but it feels to me like we could create a more extensible method...would the right answer be to add another variable to accept slight tweaks like this? Or, would we be able to leverage the existing "flags" variable to accomplish what I'm suggesting?

Now that I've written this, I guess I'm proposing that we use the existing "flags" variable, and create a new flag type every time a slight modification variant crops up for existing commands.

Sound ok? If so, I'll probably work on that this week, along with the feature to set read cache percentage. I'm also thinking that Gris may be better off leveraging this method for whatever issue he ran into while creating a volume on an SSD with Smart Array, rather than always using the "force" option.

**Comment by tasleson** [comment]
@joehandzik The flags parameter is intended to handle small tweaks to the API, but it really shouldn't be utilized for vendor specific features.  Is `aa` aka. `array accelerator` really just marketing speak for `cache`?  If that's true then I would be OK with adding a generic parameter flag value(s) for enable/disable use of system cache during volume creation.  However, from a generic API standpoint wouldn't a user want to be able to configure this for pre-existing volume(s) too, to enable/disable?

What does the acronym `BBWC` represent?

**Comment by joehandzik** [comment]
@tasleson Yup, aa is HPE-boy-aren't-we-special speak for the controller cache (or BBWC, if you will :D). It's relevant for SSD arrays and volumes in particular, because something else is enabled by default on those (a mode where IOs are sent directly to the SSD when possible). Since it happens by default, I don't really think we need a flag that forces the bypass mode to be enabled, but effectively I'd want a mode to ensure that controller caching happens for a given volume.

To your second point, I suppose a user might like to enable/disable the controller cache on existing volumes. My priority is going to be to enable array acceleration at creation time, but I think it's worth pinning a separate API call for changing configuration on an existing volume. I plan to add the acceleration type to the volume_info feature too, so users would know what mode they're in.

**Comment by cathay4t** [comment]
@joehandzik Sounds like we are discussing this PR #16 which add functions like `volume_write_cache_policy_set()` might be what you need.

**Comment by cathay4t** [comment]
BBWC == Battery Backed Write Cache.

**Comment by joehandzik** [comment]
@cathay4t That gets us some of the way there, but I'd still like to enable users to make that decision at creation time if they know what they're doing. For that particular change, we'll need to add an option to enable the BBWC on a per-volume basis. I don't think the code you have now will actually apply caching policies to the volumes, but I'll need to give the option you've found a try (I wasn't aware of the 'nbwc' option).
