### ISSUE TITLE
disk.location should be accessable by lsmcli.

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#109]
BTW, all the disks in sim plugin are using the same location, try to change it meanwhile.

Just note down, I(Gris) will take care of this issue.

**Comment by joehandzik** [comment]
You want a separate command to query the data, or add it into the default 'lsmcli ld' output? I'm assuming the former, the latter is a bit redundant since an existing entry in that table has the same data already.

**Comment by cathay4t** [comment]
I intend to have it listed in 'lsmcli ld -s' mode.

**Comment by cathay4t** [comment]
@joehandzik Just noticed you assigned to yourself. Sorry I completely forgot this issue.
Tip: add location to `DISK_HEADER` and `DISK_COLUMN_SKIP_KEYS` of `data_display.py`.

**Comment by joehandzik** [comment]
Just trying to clean out the issue backlog to help speed along a release. :) Thanks!

**Comment by cathay4t** [comment]
Tony is on vacation this week. We could get a new release next week.

**Comment by joehandzik** [comment]
I figured he was OoO, he hasn't responded to anything for all of this week. No rush, we want to get this one right since it's likely to have many more eyes on it once it's included in Ceph.
