### ISSUE TITLE
Docs - Docker Compose Example

### ISSUE THREAD

**Issue by wattsteve** [libstorage/libstoragemgmt#123]
I'm trying to figure out how to use this with Compose and Swarm. Is there a simple compose example that you could point me to that shows how to describe usage of the Docker LibStorage volume plugin with a standard interface like NFS or iSCSI in YAML?

**Comment by joehandzik** [comment]
Possibly a stupid question, but...do you actually mean to be asking this question in the libstoragemgmt github? OR, do you actually mean to be asking about this project: https://github.com/emccode/libstorage

I came across that emccode repo a while back, wondered if anyone would confuse it with libstoragemgmt. The libstorage repo has more clear claims about Docker compatibility. From your question, it's not clear to me what you're actually trying to accomplish (and that probably means that libstoragemgmt isn't the right tool for the job).

**Comment by wattsteve** [comment]
@joehandzik Aargh. You're completely correct. Closing and #facepalm

**Comment by joehandzik** [comment]
Go figure, a third option! I think we all might need to get more creative with our storage library naming...
