### ISSUE TITLE
Make the return value documentation clearer

### ISSUE THREAD

**Issue by tasleson** [libstorage/libstoragemgmt#126]
Follow what is established in 9969134f3d37ea26d68d8443c25726ca96c8b1cb by @BlaineEXE

**Comment by joehandzik** [comment]
@BlaineEXE, hey, if you have some spare cycles, I think your doxygen expertise would be appreciated in getting this done.

**Comment by BlaineEXE** [comment]
I may not be able to get to this today, but I think this week is going to be the best time to fit it in. I'll do what I can. If you or Tony have any inputs about where is best to start first and/or what items have priority, I will be sure to start there.

**Comment by tasleson** [comment]
@BlaineEXE Thanks for helping out with this.  I was thinking about starting in the include directory starting with `libstoragemgmt.h` and then walking through the other header files.

**Comment by BlaineEXE** [comment]
I see that there are some functions (specifically in libstoragemgmt_systems.h) that have possible return values recorded. Doxygen allows the `/retval` tag for listing return values. While I'm working on this, it's pretty easy to make this change. Is this something you'd like to see me move forward with?

![image](https://cloud.githubusercontent.com/assets/3989526/14894352/c378a8fc-0d38-11e6-964f-a87fb7aaef6b.png)

**Comment by tasleson** [comment]
My vote would be yes, thanks!

**Comment by joehandzik** [comment]
@tasleson, would we consider this closed, given Blaine's commit last week?

**Comment by tasleson** [comment]
@joehandzik Yes, lets close.
