### ISSUE TITLE
C unit test `test_local_disk_link_type` is not enabled.

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#134]

**Comment by cathay4t** [comment]
Fixed in 5e611bd455206183ae1d4ff1c7e25eb3d1355cb8

**Comment by joehandzik** [comment]
Closing this, since you added the fix (as documented). Lemme know if you'd rather not have me closing these, I'm just trying to keep this pruned so I know what is still outstanding for 1.3.
