### ISSUE TITLE
[RFC] How should we generate document?

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#142]
Currently the doxygen favored format:

```
    ## Called when we are ready to initialize the plug-in.
    # @param    self                    The this pointer
    # @param    uri                     The uniform resource identifier
    # @param    plain_text_password     Password as plain text
    # @param    timeout_ms              The timeout in ms
    # @param    flags                   Reserved for future use, must be zero.
    # @returns None
```

is conflicting with PEP8:

```
E266 too many leading '#' for block comment
```

And, personally, I am not a fan of doxygen.

My proposal of document system is:
- C
  - Use [kernel-doc](https://www.kernel.org/doc/Documentation/kernel-doc-nano-HOWTO.txt) tool from linux kernel to generate manpage for every function. 
  - Manually create manpage for `libstoragemgmt.h(3)` which include workflow, sample code, and all function names. Explains used constants in functions.
- Python
  - Use docstring for every function, class, property.
  - In docstring of `lsm` module, provides workflow, sample code.

**Comment by cathay4t** [comment]
For http://libstorage.github.io/libstoragemgmt-doc/ website, we simply suggest user to API use manpage or python `help()` function.

If html document is mandatory, I could create some scirpt to extract above document into markdown.

**Comment by mulkieran** [comment]
sphinx is the Python standard these days. I can't claim to be a fan of it, but I do use it for my own projects.

The results are mixed: http://pythonhosted.org/justbytes/index.html.

**Comment by cathay4t** [comment]
@mulkieran Thanks. I will give a sphinx a try. The kernel is also using sphinx now.

**Comment by cathay4t** [comment]
The sphinx seems doesn't have good way for C documentation in code comments. The kernel is using `kernel-doc` tool to generate rst files from C source code comments and sphinx takes work from there.

The kernel way seems a quite complex setup of sphinx to me. I will try manpage only way first.

**Comment by cathay4t** [comment]
Closing. Please continue discussion in PR #240. Thank you.

**Comment by tasleson** [comment]
This has been merged.
