### ISSUE TITLE
Memory leak detected during Fedora armv7hl package 1.3.1  build

### ISSUE THREAD

**Issue by tasleson** [libstorage/libstoragemgmt#151]
See: https://kojipkgs.fedoraproject.org//work/tasks/5299/14045299/build.log

I'm thinking we may want to disable valgrind testing in the normal case, so we don't fail to build a package when something we depend on has an issue.

**Comment by joehandzik** [comment]
I think you're right.

**Comment by cathay4t** [comment]
I will add option or variable to skip valgrind check.

**Comment by tasleson** [comment]
Packages have been submitted to `testing` and are currently pending for F23, F24 and el6.  I changed the spec file:

-%bcond_without test
+%bcond_with     test

To skip the `make check` to get the packages built.

**Comment by cathay4t** [comment]
OK. Fix in 1.4.

**Comment by cathay4t** [comment]
Fixed in #152 by adding configure option to skip memory leak check.
