### ISSUE TITLE
deb_dependency file is missing three dependencies

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#164]
Even after running "sudo apt-get install `cat deb_dependency`", these three dependencies are unsatisfied:

- python-yaml
- libmicrohttpd-dev
- libjson-c-dev

I'll fix it when I'm done with the debian packaging (hoping within the next week or two).

**Comment by tasleson** [comment]
@joehandzik Can you double check on this.  @cathay4t removed the restful service API df541417443ade9de6ff1dfa3463f42ceea11b8c  that required `libmicrohttpd-dev` and `libjson-c-dev`.  `python-yaml` is not required to build and test.  It's only required if you want to output detailed stats during test.  I'm not seeing any of these in the configure file too.

**Comment by tasleson** [comment]
@joehandzik If you are building from a git tree you may want to do a `git clean -fxd` && `./autogen.sh` **after you make sure you don't have any uncommitted work in your tree**.

**Comment by joehandzik** [comment]
Thanks for the bold highlight, btw. ;P

I found the issue. Ritesh's debian/control file still has those three dependencies in it for libstoragemgmt. I'll pull them out. Thanks for the reality check! I forgot that those dependencies were only for the restful service...
