### ISSUE TITLE
Missing capability in hpsa plugin: LSM_CAP_DISK_VPD83_GET

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#168]
Too much going on, can't believe I missed this. In 1.3, the Smart Array plugin will not list the VPD83 capability (I don't think any plugin lists it, mind you) so I client has no way of getting the VPD83 data via the API (except for blindly assuming that the plugin supports it).

I'll fix. I'm glad we're doing another release at the end of August. :)

**Comment by cathay4t** [comment]
Closed as #169 merged.
I also fixed the MegaRAID plugin for this missing capability.

Thanks Joe!
