### ISSUE TITLE
Smart Array and MegaRAID plugins fail geteuid check

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#172]
Hey guys,

Back on the Debian build, and I have .debs building but...it doesn't look like we're running as the correct user on Debian Jessie (probably all Debian distros). I need to do more investigation, but the upshot is that any attempt to run hpsa:// or megaraid:// is failing with:

INVALID_ARGUMENT (101): This plugin requires root privilege both daemon and client

I'll report back when I have more info. I've never seen this issue on Rhel/Centos.

**Comment by tasleson** [comment]
@joehandzik What do the contents of the `lsmd.conf` file and `libstoragemgmt.service` show for your deb package?

**Comment by joehandzik** [comment]
@tasleson Fair question, but I'm reproducing this without the package now (via a simple 'make install') so I don't think it has anything to do with the deb. 

libstoragemgmt.service shows User=root as expected, and lsmd.conf shows allow-plugin-root-privilege = true as well.

The issue isn't with the daemon as best I can tell, sim:// and targetd:// attempt to run at least. It has something to do with the plugin permissions, I believe. hpsa.conf shows require-root-privilege = true, so that's not the problem either...

**Comment by tasleson** [comment]
@joehandzik I'm assuming you are running the `lsmcli` as root, yes?

**Comment by joehandzik** [comment]
Yes indeed.

LSMCLI_URI=hpsa://
sudo -E lsmcli ls
sudo -E lsmcli p
etc...

All fail the same way. :/

**Comment by tasleson** [comment]
@joehandzik If the daemon is running as root and the client is running as root and the config files are correct, I'm at a loss at the moment.  Anything interesting in the syslog/journal?

**Comment by tasleson** [comment]
```python
if os.geteuid() != 0:
            raise LsmError(
                ErrorNumber.INVALID_ARGUMENT,
                "This plugin requires root privilege both daemon and client")
```

**Comment by joehandzik** [comment]
Nope, not unless the output would be going somewhere other than /var/log/syslog.

I'll keep looking, and I'll update if I find something useful.

**Comment by joehandzik** [comment]
Ah, sim:// doesn't require root. That explains why it still works.

**Comment by joehandzik** [comment]
User id comes out as 119, which is apparently the 'libstoragemgmt' user. So IS this actually some kind of permissions issue with that user?

**Comment by joehandzik** [comment]
Ok, I have *some* answers. 

I went and poked around at...stuff...and the most useful piece of information (something I should have taken more seriously in hindsight) is that my lsmd process (according to a 'ps aux') was running under user 'libstoragemgmt'. That explains the user id information that I posted here a minute ago, and means that for whatever reason the libstoragemgmt service is being started under the libstoragemgmt user (at least via the Debian packaging). The unfortunate part is that it seems that the original process never actually stopped despite uninstalling the packaging via dpkg.

Is there any context where the libstoragemgmt service should be owned by the libstoragemgmt user instead of root? If not, I guess I need to make sure that doesn't happen again in Debian-land.

**Comment by cathay4t** [comment]
Only when these conditions are all meet, could a plugin be run as root user:
 1. The `lsmd` is running as root user.
 2. The `lsmd.conf` (man 5 lsmd.conf) has `allow-plugin-root-privilege = true;`.
 3. Plugin config `<plugin_name>.conf` has `require-root-privilege = true;`.
 4. API user(including lsmcli) is root (`uid == 0`)

Even with 1) and 2), if no plugin config indicate `require-root-privilege`, `lsmd` will degraded itself to `libstoragemgmt` user.

When ever you got error `INVALID_ARGUMENT (101): This plugin requires root privilege both daemon and client`, please check the output of:

```
ps -ef|grep lsmd
find /etc/lsm -type f -exec grep -H root-privilege {} \;
```

**Comment by joehandzik** [comment]
So, I guess my issue boils down to the fact that lsmd is not always defaulted to running as the root user. It seems like every time I install via package (rather than installing from source) that's what I end up with...I checked my Centos7 VM too, and it also had lsmd running as libstoragemgmt user (I installed there via yum).

If there are conditions where lsmd may be running in a way that a user could not use it for Smart Array or MegaRAID, we're going to have issues where users do a package install alongside Ceph or lustre or whatever solution I put this in, and simply start up their software. It sounds like they'd have a bad experience, because libstoragemgmt would not work for them without restarting the daemon themselves as root. I'd like to avoid that...

**Comment by cathay4t** [comment]
Current rpm post scripts of plugins are supposed to restart lsmd which should not have the issue you mentioned.

@joehandzik May I have the steps you were using to reproduce this issue?

**Comment by joehandzik** [comment]
@cathay4t Ok, now that I've played with this a bit more I think I understand what my issue was on Centos. Here's how I got myself into trouble:

1. Did an initial 'yum install libstoragemgmt'
2. Went and forgot that I ever did a yum install of libstoragemgmt
3. Built and installed libstoragemgmt from source
4. Never reloaded the daemon

I retried with these steps:

1. 'yum install libstoragemgmt'
2. Ensure that lsmd is running as libstoragemgmt
3. 'yum install libstoragemgmt-hpsa-plugin'
4. Ensure that lsmd is running as root

The above steps worked as expected. So, if I do have an issue with the packages not running with the correct permissions, it's Debian-only. I'll look into that, but for now it seems Centos is ok.

HOWEVER, I found something else that I thought was a bit wrong. When I do the initial 'yum install libstoragemgmt', lsmd does not start until I reboot my VM. Is that expected behavior? If not, I'll open a separate issue so we can track it.

**Comment by cathay4t** [comment]
@joehandzik For newly installed lsmd, it will not start itself via rpm postscript intentionally. The reason you got it autostarted after reboot is [systemd autostart preset][1].

For the Centos 7 you are using:

```bash
[fge@el7r ~]$ grep -H libstoragemgmt /usr/lib/systemd/system-preset/*
/usr/lib/systemd/system-preset/90-default.preset:enable libstoragemgmt.service
```


[1]: https://www.freedesktop.org/software/systemd/man/systemd.preset.html
