### ISSUE TITLE
Bash completion not working

### ISSUE THREAD

**Issue by tranceitionalMynd** [libstorage/libstoragemgmt#178]
LSM Version: 1.3.2 (built from source) and 1.2.3 (install from OS DVD)
Linux Distro: RHEL 7.2
Architecture: x86_64

Observed behavior:

When I type lsmcli li+tab, I don't have an expnsion for the 'list' option of lsmcli.

Expected behavior:

My understanding is that lsmcli li+tab should expand to 'list'.

**Comment by cathay4t** [comment]
@tranceitionalMynd Thanks for reporting this issue. But it works from my end(RHEL 7.2 + libstoragemgmt 1.3.3)
```bash
[fge@el7r libstoragemgmt]$ ./autogen.sh
[fge@el7r libstoragemgmt]$ ./configure
[fge@el7r libstoragemgmt]$ make -j5
[fge@el7r libstoragemgmt]$ sudo make install
[fge@el7r libstoragemgmt]$ find /usr/share/bash-completion/|grep lsmcli
/usr/share/bash-completion/completions/lsmcli
[fge@el7r libstoragemgmt]$ logout
Connection to el7r closed.
[fge@Gris-Laptop ~]$ ssh el7r
[fge@el7r ~]$ lsmcli list --type ^C
[fge@el7r ~]$ which lsmcli
/usr/local/bin/lsmcli
```

Could you start a new bash(logout and relogin) after installation, it allow bash-completion to load new
configure for lsmcli?

If you still have issue, please provide output of:
```bash
find /usr/share/bash-completion/|grep lsmcli
rpm -q bash-completion
```

**Comment by cathay4t** [comment]
Closing as it works for me and no feedback for months.
