### ISSUE TITLE
/var/run/lsm/ipc directory not created in spec files generated from source

### ISSUE THREAD

**Issue by tranceitionalMynd** [libstorage/libstoragemgmt#179]
LSM Version: 1.3.2 (rpm built from source)
Distribution: RHEL 7.2

How to recreate from 1.3.2 source build and re-packaging:
run autogen.sh
configure
make
Utilize packaging/libstoragemgmt.spec
copy tarball to ~/rpmbuild/SOURCES
package rpms from the spec file with rpmbuild -ba libstoragemgmt.spec

1.3.2 source rpm Installation:
Uninstall the OS package of LSM:
yum uninstall libstoragemgmt (this removes /var/run/lsm/ipc)
Install the package built from source:
yum install ./libstoragemgmt*.rpm (the package built from source does not recreate /var/run/lsm/ipc)

Observed behavior:

The 1.2.3 libstoragemgmt rpm from the RHEL 7.2 DVD re-creates the /var/run/lsm/ipc directory, but the 1.3.2 rpm packaged from source does not.

Expected behavior:

The /var/run/lsm/ipc directory (or configured ipc directory) should be created in spec files generated from source.

**Comment by cathay4t** [comment]
@tranceitionalMynd It works for me:

```bash
[fge@el7r ~]$ ls /var/run/lsm
ls: cannot access /var/run/lsm: No such file or directory

[fge@el7r ~]$ make dist

[fge@el7r ~]$ rpmbuild -ta libstoragemgmt-1.3.3.tar.gz --without test

[fge@el7r ~]$ sudo yum install /home/fge/rpmbuild/RPMS/x86_64/libstoragemgmt-1.3.3-1.el7.x86_64.rpm /home/fge/rpmbuild/RPMS/noarch/libstoragemgmt-python-1.3.3-1.el7.noarch.rpm /home/fge/rpmbuild/RPMS/x86_64/libstoragemgmt-python-clibs-1.3.3-1.el7.x86_64.rpm

[fge@el7r ~]$ ls /var/run/lsm
ipc

```
Could you try it again and provide output of this command:

```bash
rpm -q libstoragemgmt --scripts
```

**Comment by cathay4t** [comment]
Closing as it works for me and no feedback for months.
