### ISSUE TITLE
BUG: Python Libary conflict with C library

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#183]
In Python API, we have `export_fs()` with `anon_uid=NfsExport.ANON_UID_GID_NA`, here ANON_UID_GID_NA is -1.

In C API, we have `lsm_nfs_export_fs()` takes `uint64_t anon_uid`, clearly `LSM_NFS_EXPORT_ANON_UID_GID_NA(-1)` is not possible here.

Any suggestion?

**Comment by cathay4t** [comment]
We could mark `export_fs()` as deprecated and introduce new API `lsm_nfs_export_create()`.

**Comment by tasleson** [comment]
@cathay4t If you look at the header libstoragemgmt_nfsexport.h you will see the following comment:

``` C
/**
 * Because the nfs export functions use an unsigned data type these values
 * will be represented as (2**64-1 and 2**64-2 respectively)
 */
```

if you try some C code out you will see:

``` C
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>


int main() {

    uint64_t foo = -1;
    uint64_t bar = -2;

    if (foo == -1 ) {
        printf("Compare does match for -1\n");
    }

    if (bar == -2 ) {
        printf("Compare does match for -2\n");
    }

    if (foo == 0xFFFFFFFFFFFFFFFF) {
        printf("Compare does match for 0xFFFFFFFFFFFFFFFF\n");
    }

    if (bar == 0xFFFFFFFFFFFFFFFE) {
        printf("Compare does match for 0xFFFFFFFFFFFFFFFE\n");
    }

    return 0;
}
```
``` 
Compare does match for -1
Compare does match for -2
Compare does match for 0xFFFFFFFFFFFFFFFF
Compare does match for 0xFFFFFFFFFFFFFFFE
```

I think we are OK with what we have.  Is it ideal or would we do it this way if we caught it sooner, absolutely not.

**Comment by tasleson** [comment]
The only issue I can think of is that we didn't account of the representation to be different when crossing languages.  So python client with C plugin. When the value gets serialized across JSON we could end up with 0xFFFFFFFFFFFFFFFF on the python side which wouldn't match.  To accommodate this we could add separate properties on the NfsExport class to translate anonguid/gid to -1, -2 when read if the current values are 2**64-1 and 2**64-2 respectively.

**Comment by tasleson** [comment]
See ef4c7ed102cafa74f867da688496dfb52e9e9a4b for more information.  I think we can make this better by adding properties on python NfsExport class.

**Comment by cathay4t** [comment]
Close this issue, please continue the discussion in PR #184
