### ISSUE TITLE
Migrate from sf.net to github

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#2]
Just for tracking the migration progress:
 * Document: (in code tree or separate as wiki, Gris: prefer in code tree)
  * top folder readme file.
  * User guide
  * Dev guide
   * Lib dev guide. (C and Python)
   * C Plugin dev guide.
   * Python Plugin dev guide.

 * Wiki:
  * Known issue/bugs
    List known issue of plugin or arrays. 
    Like HDS VPD83 issue which could gone if HDS fix it in their SMI-S provider.

  * Array configures.
    Documents which we cannot add them into manpage:
    Like how to configure EMC SMI-S provider.

 * RPM SPEC upstream URL update.
 * Announcement:
   * maillist
   * sf.net frontpage.

**Comment by cathay4t** [comment]
All set except mail list auto reply.
Will set 'auto-reply' on sf.net mail list next week(09 April 2015).

**Comment by cathay4t** [comment]
TODO:
* Email Gmane to request mailing list archive and mailing list address update.
* Shutdown sf.net mailing list for good.

**Comment by tasleson** [comment]
With all the controversy with sf.net as of late, I'm tempted to delete our historical project from sf.net in the near future.

**Comment by cathay4t** [comment]
We can do in 1.3 release which I will merge all existing sf.net wiki to github pages.

**Comment by cathay4t** [comment]
To remove our project from sourceforge, we need to create some kind of [support ticket][1],
so I just delete everything there and only leave a notice about moved to github there.

Closing this issue.

[1]: https://sourceforge.net/p/forge/documentation/How%20to%20Remove%20a%20Project/
