### ISSUE TITLE
Feature request - Serial Number for physical disks via local_disk API

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#203]
We have a partner that would like to extract disk serial numbers without using a vendor-specific plugin. This shouldn't be too tough, I'll get to it as soon as I can.

**Comment by cathay4t** [comment]
The SCSI SPC `READ MEDIA SERIAL NUMBER` command should do. I will take care this.

**Comment by cathay4t** [comment]
Opps. As sg3_utils indicates ` It is not an mandatory command and the author has not seen any SCSI devices that support it.`. Will find another way.

**Comment by cathay4t** [comment]
vpd 0x80 `Unit Serial Number VPD page` could be used.

**Comment by joehandzik** [comment]
That was the path I had started down (vpd80), yeah. It would look really similar you the existing vpd83 code. I have this half started and can probably finish it tomorrow...maybe I take this one and you poke at the LED states? If you already have code in progress too, it's alright if you beat me to this.

On Sep 7, 2016, at 10:07 PM, Gris Ge <notifications@github.com<mailto:notifications@github.com>> wrote:


vpd 0x80 Unit Serial Number VPD page could be used.

-

**Comment by cathay4t** [comment]
No, I haven't code anything yet. You may continue on this. I will work on the SES LED feature.

**Comment by joehandzik** [comment]
@cathay4t Sounds good!
