### ISSUE TITLE
Feature request - Ident/Fault LED state request via local_disk API

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#204]
Similar to the last request, there's a prospective libstoragemgmt user that would like to know the current state of each LED that corresponds to a physical disk, also without vendor-specific code. This should be possible via the SES interface that @cathay4t created.

**Comment by cathay4t** [comment]
I will take care of this.

**Comment by cathay4t** [comment]
@joehandzik I drafted the patch(still have some tests running) https://github.com/cathay4t/libstoragemgmt/commit/423892a16065b518f1dd0d1a45419d5a322cd253, could you test it on hpsa? 
It works well in our lab for mpt2sas enclosure.

**Comment by cathay4t** [comment]
Oh, forgot to mention. `sudo lsmcli ldl` would do the trick.

**Comment by cathay4t** [comment]
Closing this issue against PR #217
