### ISSUE TITLE
The LsmError classname in traceback should be lsm.LsmError instead of lsm._common.LsmError

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#206]
``` bash
[fge@Gris-WS ~]$ python -c 'import lsm; raise lsm.LsmError(1, "haha")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
lsm._common.LsmError: LIB_BUG(1): haha 
```

The traceback should use `lsm.LsmError`. The same problem also exists in pywbem upstream, if we find a fix, we'd better send a PR to pywbem also.

**Comment by tasleson** [comment]
If you accept the expected name it does indeed work:

```python
import lsm
import traceback

try:
    raise lsm.LsmError(1, 'what the what')
except lsm.LsmError as le:
    msg = str(traceback.format_exc())
    print('Caught it:\n%s' % msg)

```

Produces:
```text
Caught it:
Traceback (most recent call last):
  File "simple.py", line 5, in <module>
    raise lsm.LsmError(1, 'what the what')
lsm._common.LsmError: LIB_BUG(1): what the what

```
But it would be better if the stack trace came back with `lsm.LsmError`.

**Comment by tasleson** [comment]
After researching this one some, I've not located a way to address this.

**Comment by cathay4t** [comment]
Me neither. I tried to trick traceback module but apparently python is using a C extension for error handling. Haven't got a chance to ask upstream or read C code yet.

**Comment by tasleson** [comment]
AFAIK this one we cannot solve, closing.
