### ISSUE TITLE
Required RPM bloat

### ISSUE THREAD

**Issue by BlaineEXE** [libstorage/libstoragemgmt#215]
I've noticed that from version 1.2.3 to version 1.3.4, there is what I'll call 'required RPM bloat'. When installing the `libstoragemgmt` package in 1.2.3, the `libstoragemgmt-python` package is a dependency. In version 1.3.4, the `libstoragemgmt-python` dependency still exists, but the `libstoragemgmt-python-clibs` dependency has also been added. This poses problems for updating from one version to the next.

For example, I build the latest RPMs (1.3.4 currently) and distribute them with an install script for automatic updating. A `yum update <all_lsm_packages>` operation fails with the message below even though I specify the `libstoragemgmt-python-clibs` file as part of 'all_lsm_packages'. At the heart of it, I think this functionality is non-ideal from yum, but it seems to me that the libstoragemgmt project could improve the user experience in the case I'm experiencing by only adding new RPMs to the build when they are non-required dependencies to avoid these issues.

```
Error: Package: libstoragemgmt-python-1.3.4-1.el7.noarch (/libstoragemgmt-python-1.3.4-1.el7.noarch)
           Requires: libstoragemgmt-python-clibs
```

To add more detail, packages I have installed from 1.2.3:
- `libstoragemgmt`
- `libstoragemgmt-python`
- `libstoragemgmt-hpsa-plugin`

When I do `yum update -y libstoragegmt*.rpm`, using 1.3.4 RPMs I expect all packages to be updated, and the yum output indicates the existing 3 will be updated. However, the failure message above also occurs, because the new requirements are:
- `libstoragemgmt`
- `libstoragemgmt-python`
- `libstoragemgmt-python-clibs`
- `libstoragemgmt-hpsa`

I don't see why the `libstoragemgmt-python-clibs` package is required to be an additional package dependency. Why can't it be rolled into either `libstoragemgmt` or `libstoragemgmt-python`?

**Comment by cathay4t** [comment]
I will investigate no this.

**Comment by cathay4t** [comment]
It works well for me:
https://gist.github.com/cathay4t/ac1d0d710a803e347911f590eb2e8180

The `libstoragemgmt-python` is noarch while `libstoragemgmt-python-clibs` is C compiled, so it should be split into two pkgs.

**Comment by cathay4t** [comment]
@BlaineEXE Could you try again and provide detail log if failed? Thank you.

**Comment by BlaineEXE** [comment]
The issue I'm describing specifically occurs when I build the latest RPMs and copy them to host machines, installing them locally (from the copied RPM files) and not from a repository.

**Comment by cathay4t** [comment]
@BlaineEXE I am using RHEL 7.2.

**Comment by BlaineEXE** [comment]
I can confirm the behavior you see on RHEL 7.2. I don't think yum behaves the same way on RHEL 6, but I don't have a system up right now to test that.

**Comment by cathay4t** [comment]
@BlaineEXE `yum install` on RHEL 6 acted the same as RHEL 7 did. And the lsm upgrade works well on RHEL 6.8:
https://gist.github.com/cathay4t/b98431ca837038a46d10d3e45a538b44

**Comment by cathay4t** [comment]
I am guessing you are using command:
```
sudo yum install /home/fge/rpmbuild/RPMS/noarch/*-1.3.5*
```
In stead of
```
sudo yum install /home/fge/rpmbuild/RPMS/*/*-1.3.5*
```

And the former one does not include `libstoragemgmt-python-clibs` which triggered the issue you mentioned.

If you could provide me the detail log of failed yum, I may spot out the root cause.
