### ISSUE TITLE
1.3.5 Source Code release has 1.3.4 version number

### ISSUE THREAD

**Issue by BlaineEXE** [libstorage/libstoragemgmt#216]
The "Source code" release for version 1.3.5 has the 1.3.4 version specified. I am unsure if 1.3.5 code changes have made it to this tarball.

![image](https://cloud.githubusercontent.com/assets/3989526/19002708/e50fe396-8712-11e6-8b56-4035fe8ef0cd.png)

Snippet of `configure.ac`
```
dnl Process this file with autoconf to produce a configure script.
dnl Copyright (C) 2011-2016 Red Hat, Inc.
dnl See COPYING.LIB for the License of this software

AC_INIT(
    [libstoragemgmt], [1.3.4], [libstoragemgmt-devel@lists.fedorahosted.org],
    [], [https://github.com/libstorage/libstoragemgmt/])
AC_CONFIG_SRCDIR([configure.ac])
AC_CONFIG_AUX_DIR([build-aux])
AC_CONFIG_HEADERS([config.h])
AC_CONFIG_MACRO_DIR([m4])
dnl Make automake keep quiet about wildcards & other GNUmake-isms
AM_INIT_AUTOMAKE([-Wno-portability subdir-objects])
AM_MAINTAINER_MODE([enable])
# Enable silent build when available (Automake 1.11)
m4_ifdef([AM_SILENT_RULES],[AM_SILENT_RULES([yes])])
PKG_PROG_PKG_CONFIG
```

**Comment by BlaineEXE** [comment]
It looks like both "Source code" options (tar.gz and zip) are affected, but the "libstoragemgmt-1.3.5.tar.gz" download shows `[1.3.5]` in `configure.ac`

**Comment by tasleson** [comment]
The tag is on the wrong commit.  Github generates the two files that are incorrect based on the tag.  However, some other files didn't get updated too for the release:

* NEWS
* packaging/libstoragemgmt.spec.in

I'll re-roll this release in a little bit.

**Comment by BlaineEXE** [comment]
Thanks, Tony!

**Comment by tasleson** [comment]
@BlaineEXE OK, Gris already did releases for fedora, so I only changed the tag to be on the correct commit.  We can't change the contents of the release that is already out in the wild unless we make a 1.3.6 instead.
We will correct NEWS & packaging/libstoragemgmt.spec.in when we roll the next one.

The source code zip and tag.gz should be correct now.

**Comment by tasleson** [comment]
Just to be specific the 1.3.5 tag was on 2ce5a35 it's now on 54eb290, which is the commit the bumped `configure.ac`.

**Comment by BlaineEXE** [comment]
The `configure.ac` shows 1.3.5 now. I think this can be marked fixed and closed.
