### ISSUE TITLE
hpsa plugin error when a disk has been hot removed

### ISSUE THREAD

**Issue by cvedel** [libstorage/libstoragemgmt#218]
When a disk has been hot removed, hpssacli does not include the port number in the physical drive section:
```
      physicaldrive 0:6
         Box: 0  
         Bay: 6  
         Status: Failed
         Last Failure Reason: Hot removed 
         Drive Type: Data Drive
         Interface Type: Solid State SATA
         Size: 80.0 GB 
         Drive exposed to OS: False
         Native Block Size: 4096
         Firmware Revision: 4IWTHPG1
         Serial Number: PHWA626204HF080BGN
         Model: ATA     VK0080GEYJN
         SATA NCQ Capable: True
         SATA NCQ Enabled: True
         Maximum Temperature (C): 65 
         Usage remaining: 100.00% 
         Power On Hours: 437
         SSD Smart Trip Wearout: False
         PHY Count: 1
         PHY Transfer Rate: Unknown 
         Drive Authentication Status: Not Applicable
         Sanitize Erase Supported: False
```
This triggers a ValueError exception in the hpsa plugin `_hp_disk_to_lsm_disk` function when it splits the physical drive id because three values are expected but only two are returned:
```
disk_port, disk_box, disk_bay = disk_num.split(":")
```
This is with the following version of hpssacli:
```
# hpssacli version

   HPSSACLI Version: 2.40.13.0
   SOULAPI Version: 8.4.13.0
```

**Comment by cathay4t** [comment]
@cvedel Thanks for the report.

@joehandzik I have no physical access to any HPSA cards to remove disks, is that possible for you guys to work on a fix for this issue? Thank you.

**Comment by joehandzik** [comment]
@cathay4t Yup, I'll take care of it. Thanks for the report, @cvedel!

**Comment by joehandzik** [comment]
@cvedel If you have the time to check it out, my fix attempt is here: https://github.com/joehandzik/libstoragemgmt/tree/wip-fix-issue-218

I ran out of time to test it today, but I'll test it tomorrow if you don't get to it first.

**Comment by cvedel** [comment]
@joehandzik This fixes the problem for me. Thanks!

**Comment by joehandzik** [comment]
@cvedel Good news, thanks. I have opened an issue on the HPE side against hpssacli, intending for this workaround to be unnecessary for future versions of hpssacli.

**Comment by cathay4t** [comment]
@joehandzik Could you submit your patch as PR as an workaround before hpssacli fix them?
