### ISSUE TITLE
ssacli version 2.60.18.0 changes to "Logical/Physical Block Size" from "Native Block Size"

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#223]
Good news is that our parser isn't totally broken now that I'm on the right unreleased versions of ssacli...bad news is that they're still changing key names on me.

**Comment by tasleson** [comment]
@joehandzik It would be great if you could bubble this issue up the chain.  Unless we get some type of useful & stable API (regardless of what it is) we will always be behind and perpetually broken (potentially) for each new release of the command line tool.  Having to support all the different known versions is a PITA too.

**Comment by joehandzik** [comment]
I agree with you. The good thing here is that I'm testing this one WAY before it'll be released, so worst case I'll have the fix in place before a customer would see it. I may even have a chance to get the old entry back, alongside the new entry.

Of course, this may introduce lots of cases where users of older libstoragemgmt versions will simply be broken with brand new versions of hpssacli. I have raised this issue with Microsemi, but for a variety of reasons, they are unwilling to stop the changes at this time. I'll keep the pressure on by writing bug reports every time I see something like this, but it may be beneficial for Red Hat to also push Microsemi to knock this off (from what I understand, there were Microsemi managers meeting with Red Hat folks within the last couple of months). If they understand that these problems make their hardware less attractive to both of our companies, we may have a better shot.
