### ISSUE TITLE
"test/trusted.yaml" should not in current project.

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#225]
@tasleson If certain PR add their url into this one. The CI test will allow it.
We should move it to lsm-ci project.

**Comment by tasleson** [comment]
The lsm-ci code fetches the trusted file from:

``` Python
# Full path to trusted file on repo itself
TRUSTED_REPO_REMOTE = os.getenv(
    'TRUSTED_REPOS_REMOTE',
    'https://raw.githubusercontent.com/' +
    'libstorage/libstoragemgmt/master/test/trusted.yaml')
```
so until the PR is merged any changes to it would be ignored.

**Comment by cathay4t** [comment]
Oh, I didn't read that part. Thanks. Closing this issue.
