### ISSUE TITLE
Support exposing multiple systems of data

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#229]
I'm not sure on the exact best way to implement this, but going forward you could definitely see cases where a user would want to query multiple vendor devices without switching between plugins explicitly. Could we enable, at the very least, the ability to list multiple endpoints to query? Something like:

LSMCLI_URI="hpsa://,megaraid://"

Any other thoughts would be appreciated!

**Comment by tasleson** [comment]
Whatever the approach is, it needs the ability to accommodate a separate URI and password for each different device.

**Comment by joehandzik** [comment]
@tasleson Would a config file be more appropriate, then?

**Comment by tasleson** [comment]
@joehandzik Yeah, probably.  We actually have some support for a config file. 

``` Python
    def _read_configfile(self):
        """
        Set uri from config file. Will be overridden by cmdline option or
        env var if present.
        """

        allowed_config_options = ("uri",)

        config_path = os.path.expanduser("~") + "/.lsmcli"
        if not os.path.exists(config_path):
            return

        with open(config_path) as f:
            for line in f:

                if line.lstrip().startswith("#"):
                    continue

                try:
                    name, val = [x.strip() for x in line.split("=", 1)]
                    if name in allowed_config_options:
                        setattr(self, name, val)
                except ValueError:
                    pass
```

 Would need to enhance it.  Storing passwords in a file is problematic though.

**Comment by joehandzik** [comment]
@tasleson RE: plaintext passwords - Yeah, this is a real problem. Smart Array actually leverages an EKMS for drive encryption because of that fact (local encryption is an option too, but only as safe as access to the host filesystem is). Currently though, wouldn't a user need to add the password as an environment variable to avoid typing it in at the command line? Maybe we just need a better answer to that bit for libstoragemgmt in general.

**Comment by cathay4t** [comment]
@joehandzik Can PR #288  fix this issue?
