### ISSUE TITLE
Consistency of vpd83 and vendor extension

### ISSUE THREAD

**Issue by dwlehman** [libstorage/libstoragemgmt#239]
Is there any reassurance with regard to consistency where vpd83 and vendor extensions are concerned? I was just playing around and found that the vpd83 for an hpsa and megaraid volume both included vendor extension (as indicated by udev). This is not a problem for me, but I'm wondering if I can rely on this for all volumes.

Example python code and corresponding udev data:

```python
>>> import lsm
>>> uris = ('hpsa://', 'megaraid://')
>>> for uri in uris:
...     client = lsm.Client(uri)
...     volumes = client.volumes()
...     for volume in volumes:
...         print volume.name, volume.vpd83
... 

Logical Drive: 1: /dev/sda 600508b1001c79ade5178f0626caaa9c
VD 0: test 600605b00a5796201f9744221d0dc495
>>> 
```
```
# udevadm info --name=sda | grep ID_WWN
E: ID_WWN=0x600508b1001c79ad
E: ID_WWN_VENDOR_EXTENSION=0xe5178f0626caaa9c
E: ID_WWN_WITH_EXTENSION=0x600508b1001c79ade5178f0626caaa9c
# udevadm info --name=sdb | grep ID_WWN
E: ID_WWN=0x600605b00a579620
E: ID_WWN_VENDOR_EXTENSION=0x1f9744221d0dc495
E: ID_WWN_WITH_EXTENSION=0x600605b00a5796201f9744221d0dc495
```

**Comment by cathay4t** [comment]
In libstoragemgmt document we define `vpd83` string as `SCSI VPD83 NAA ID`, it has nothing to do with udev properties.
In most cases[1], libstoragemgmt `vpd83` string will be udev `ID_WWN_WITH_EXTENSION`.

Whatever name used by udev for disk has nothing to do libstoragemgmt API. If user want to identify disk by libstoragemgmt `vpd83` string, they should use C `lsm_local_disk_vpd83_search()` or python `lsm.LocalDisk.vpd83_search()`.

Udev is designed to support all type of disks, so they need blur definition on disk ID to support all.
For libstoragemgmt, as an API, we need to be more specific on disk ID even that might raising no support error on old/wire disks.

[1]: udev is searching wide rang of ID type, SCSI VPD83 NAA takes the second priority, right after SCSI VPD83 TGT GROUP ID. On most system, TGT group ID is not exposed, hence VPD83 NAA ID is `ID_WWN_WITH_EXTENSION`.  Please check `static const struct scsi_id_search_values id_search_list` of `systemd/src/udev/scsi_id/scsi_serial.c` for detail.

**Comment by cathay4t** [comment]
BTW, you should always use `ID_WWN_WITH_EXTENSION` as that's the ID used for `/dev/disk/by-id/wwn-<ID_WWN_WITH_EXTENSION>`.

**Comment by cathay4t** [comment]
@dwlehman Did I answer your concern?

**Comment by cathay4t** [comment]
No reply and closing.
