### ISSUE TITLE
plugin_test will fail on targetd plugin when both normal lvm vg and thinp pool configured.

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#244]
The `def _replicate_test()` invoke `self._volume_create()` which does not chose thinp pool while targetd only allows replication copy on thinp volume.

**Comment by cathay4t** [comment]
Workaround around would be remove normal lvm vg from targetd config.

**Comment by tasleson** [comment]
Targetd is getting phased out.
