### ISSUE TITLE
python3 support typo in the hpsa plugin

### ISSUE THREAD

**Issue by cvedel** [libstorage/libstoragemgmt#251]
In volume_raid_create, a call to list was added at the wrong level in an expression:
`sys_id = list(_sys_id_of_ctrl_data(sys_output.values()[0]))`
Should be:
`sys_id = _sys_id_of_ctrl_data(list(sys_output.values())[0])`
This causes a wrong pool id to be searched for (`['P', 'D', 'S', 'X', 'L', '0', 'B', 'R', 'H', '7', 'V', '0', '8', 'J']:Array:D`) and the method fails.

**Comment by joehandzik** [comment]
@cvedel You basically already have the fix figured out, are you sure you don't want to make the change and get credit for the fix? :)
