### ISSUE TITLE
HPSA plugin: Drives labeled 'Predictive Failure' register with a state of 'Other' in lsmcli

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#256]
Caught this as I was testing on a node with a drive known to be SMART tripped. I'll fix it.

**Comment by cathay4t** [comment]
@joehandzik Could you provide the output of `ssacli  ctrl all show config detail` for me to fix this issue?
Thank you.

**Comment by tasleson** [comment]
Closing as we don't apparently have the output and Joe is no longer working with storage.
