### ISSUE TITLE
Add support of NVMe for SMART.

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#265]
It's in `Log Identifier 02h` of `Admin Command Set`.

These keys might help:
 * Critical Warning
 * Available Spare vs Available Spare Threshold
 * Percentage Used (life vs vendor predicted life)
 * Composite Temperature (Feature Identifier 04h)

**Comment by cathay4t** [comment]
I am not sure when I could allocate time for this, but since I already have code for NVMe IOCTL(in my libnvme demo), it should not take a long time.

**Comment by joehandzik** [comment]
@cathay4t I have not started any work on NVMe yet, but my hope would be that NVMe supports something analogous to SMART Status. These look more like SMART attribute or device statistic analogs, which is something that we still need to figure out how to surface for SCSI and ATA as well. 

So, it would seem that all these values would go along with my planned device statistics work, and we might pinch off some of it to stick in the SMART Status local_disk command. Just my two cents.

I, too, am not sure when I'd have cycles to go and do more. I'm actually moving onto disk power control right now to have code ready for our Gen10 launch on a server that can power off individual drive bays. That's going to take up all my libstoragemgmt time slices for the next couple months, I'd imagine. So if you're not in a hurry on this, I can probably get to this sometime in Q3 or Q4 of this year.

**Comment by tasleson** [comment]
resolved with https://github.com/libstorage/libstoragemgmt/pull/455
