### ISSUE TITLE
lsmcli -h confusion prevention / consistency changes

### ISSUE THREAD

**Issue by Thetacz** [libstorage/libstoragemgmt#274]
Some of command descriptions in `lsmcli -h` are not descriptive enough to prevent confusion, could use some syncing with manpage. Also there are some inconsistencies. Examples:
```
    volume-replicate    Creates a new volume and replicates provided volume to it.
    volume-replicate-range    Replicates a portion of a volume
```
`volume-replicate` is nice, but `volume-replicate-range` could be change to something like `Replicates a portion of a volume to existing volume`, as now it seems like it will create a new one, same way as `volume-replicate`.

```
    volume-dependants-rm    Removes dependencies
```
Could be changed to `Removes dependencies from volume` to be consistent with the rest.

```
    fs-create           Creates a file system
    fs-delete           Delete a filesystem
```
Again consistency: `Creates` vs `Delete`.

```
    fs-dependants       Returns True if filesystem has a child dependency(clone/snapshot) exists
```
Probably should be `dependency (clone/snapshot exists)`.

```
    local-disk-list     Query local disk information
  -s, --script          Displaying data in script friendly way.
```
Combination of this gives more info, but there is no hint at all that there is some info hidden, probably something like `-s, --script          Displaying data in script friendly way. Sometimes gives more info` would be helpful.

**Comment by cathay4t** [comment]
Fixed in PR #311
