### ISSUE TITLE
Work with targetd guys to fix targetd plugin about fs methods

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#28]
With RHEL 7.1 targetd 0.8.1, the `btrfs subvolume list -ua <path>`
provide additional string `<FS_TREE>/` which cause targetd 0.8.1 return
empty list for `fs_list` command.

This cause all LSM fs related methods failed on targetd plugin.

Need future investigation.

**Comment by tasleson** [comment]
I've posted patches to targetd development list that allow us to pass the fs tests on my local development system.  Once those are committed and a new release to cut we should hopefully pass.  

I will patch the automated development server to run with the patches to see if we can run clean in that environment too.

**Comment by agrover** [comment]
thanks. @tasleson, 0.8.2 published. BTW both of you are collaborators on targetd now.

**Comment by tasleson** [comment]
Issue should be resolved with 0.8.2
