### ISSUE TITLE
One bad disk response causes local-disk-list to fail entirely

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#291]
Logging this here in case anyone has a different opinion, but I was walking someone through using libstoragemgmt on a Gen10 ProLiant, and we ran into an unhandled return code on his box for one of the operations executed in local-disk-list. Unfortunately, that prevents all further operations from executing. So, we'll want to do something else other than raising the errors that come out from operations in local-disk-list, IMO.

**Comment by cathay4t** [comment]
@joehandzik Good point.
How about we change lsmcli only print a error line instead of falling the whole command?

**Comment by joehandzik** [comment]
@cathay4t That's basically what I've done as a workaround. I should have self-assigned this, since I have something complete already. Just working through another bug before submitting a PR.

**Comment by tasleson** [comment]
Was the error in retrieving the list of local disks or when we were gathering more information on each disk?

**Comment by joehandzik** [comment]
@tasleson Gathering information phase. We think we actually tracked it down to an SD card that was hitting an area where we passed up an error instead of just returning NO_SUPPORT.

**Comment by cathay4t** [comment]
Closing since fix was merged.
