### ISSUE TITLE
Tracking issue for libstoragemgmt 1.5 release

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#305]
* Due to issue #283, we may need to drop support of  RHEL 6 in this releease.
 * Should we raise requirement to python2.7 since python 2.6 is not supported in upstream?
 * How about set the release date at 31 Oct 2017?

**Comment by cathay4t** [comment]
@joehandzik @tasleson Any issue you want me to fix in 1.5 release? And any input on above?

**Comment by cathay4t** [comment]
I intend to fix these issues before 1.5 release:

 *  Enable gcc checkings on c++ codes and fix all the warnings.  #303
 * Handle Pool.STATUS_VERIFYING in ONTAP and MegaRAID plugin. #26 
 *  `cert_file` into ontap and smispy plugin URI parameter.  #282

**Comment by cathay4t** [comment]
@tasleson You don't have to run covscan for me. I ran and found some issue of libsg.c code and will work on it after I back from holiday.
 * The `_sg_io_v4` is incorrect using memset: `memset(&io_hdr, 0, sizeof(struct sg_io_hdr));`
 * Adding more document for ata pass through so that future maintainer don't have to read SPC and ATS pdfs again.
 * Rename functions and constants to fit into current naming in libata files.

**Comment by cathay4t** [comment]
Covscan warnings has been fixed in PR #313

**Comment by tasleson** [comment]
@cathay4t I really dislike the idea of jettisoning EL6 just because we can't specify the same compiler flags in the configure file ref: https://github.com/libstorage/libstoragemgmt/issues/283  There should be something we can do for this...

**Comment by cathay4t** [comment]
@tasleson I tried, but no luck. We may explicitly add `-Wall` and etc CPPFLAGS without checking, but it
is seems not a best practice.
I intend to drop EL6 support are mainly because of `python-2.6`, many features we are using in python library are only exists in 2.7 or 3.x. Red Hat just happen to ported all we need into EL6. To continue supporting EL6, it requires us to test our code on EL6 python 2.6 and normal python 2.7 and python 3.x.
Considering late phrase of EL6, I don't think that worth our time.

**Comment by cathay4t** [comment]
Closing. 1.6 released.
