### ISSUE TITLE
Can you add support for packaging this in Debian as well?

### ISSUE THREAD

**Issue by seitzbg** [libstorage/libstoragemgmt#324]
I see you have RPM based spec files however nothing for Debs.  Would it be possible to add support for this as well?

**Comment by joehandzik** [comment]
Hey @seitzbg, I was working on this but as priorities shifted at work I wasn't able to continue. Here's the branch I had working for an official Debian build if you want to use it as inspiration to get something working: https://github.com/joehandzik/libstoragemgmt-1

Alternatively, you could try converting the RPM to a DEB by way of FPM (https://github.com/jordansissel/fpm). I've had success using it for some other projects I'm working on, though I haven't tried using it for libstoragemgmt.

**Comment by cathay4t** [comment]
I will take a look on this after my vacation (Feb 26 2018):
 * Provide deb package file in master branch.
 * Try to add libstoragemgmt back to debian official repo: https://tracker.debian.org/pkg/libstoragemgmt

**Comment by cathay4t** [comment]
@seitzbg The pull request https://github.com/libstorage/libstoragemgmt/pull/327 will fix this issue. I am closing this issue. For any follow up comments, please use that pull request page. Thank you.
