### ISSUE TITLE
Change out JSON C library

### ISSUE THREAD

**Issue by tasleson** [libstorage/libstoragemgmt#325]
We would like to migrate away from yajl due to lack of upstream activity.

**Comment by jumitche** [comment]
I've used jansson on other projects and found it quite easy to use, for whatever that's worth.

**Comment by cathay4t** [comment]
@jumitche Thank you. That's on our list.

**Comment by cathay4t** [comment]
The jasson cannot handle `uint64_t`: https://github.com/akheron/jansson/issues/69

Checking whether we can use rust for json processing without breaking ABI to C client.

**Comment by cathay4t** [comment]
Using rust for json processing require too much code work, don't worth it unless we fully replace c/c++ code with rust.

**Comment by tasleson** [comment]
Addressed with https://github.com/libstorage/libstoragemgmt/pull/338
