### ISSUE TITLE
PLUGIN_BUG(2): _parse_hpssacli_output(): Found duplicate line HPE E208i-a SR Gen10

### ISSUE THREAD

**Issue by mobidyc** [libstorage/libstoragemgmt#337]
Seems to be related to indentation on new Gen10 servers

```# python
Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lsm
>>> lsm_client = lsm.Client("hpsa://")
>>> print lsm_client.volumes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/lsm/_common.py", line 576, in inner
    r = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lsm/_client.py", line 405, in volumes
    return self._tp.rpc('volumes', _del_self(locals()))
  File "/usr/lib/python2.7/site-packages/lsm/_transport.py", line 154, in rpc
    (reply, msg_id) = self.read_resp()
  File "/usr/lib/python2.7/site-packages/lsm/_transport.py", line 181, in read_resp
    raise LsmError(**e)
lsm._common.LsmError: PLUGIN_BUG(2): _parse_hpssacli_output(): Found duplicate line HPE E208i-a SR Gen10 in Slot 0 (Embedded) 
>>> 
```

below the output of ssacli:
```# ssacli ctrl all show

HPE E208i-a SR Gen10 in Slot 0 (Embedded)

APPLICATION UPGRADE REQUIRED: This controller has been configured with a more
                              recent version of software.
                              To prevent data loss, configuration changes to
                              this controller are not allowed.
                              Please upgrade to the latest version to be able
                              to continue to configure this controller.



HPE Smart Array P408i-p SR Gen10 in Slot 2  (sn: PFJHD0ARC950CN)

```

**Comment by joehandzik** [comment]
Strange, we definitely have this running across various configurations of Gen10 controllers and haven't seen issues. I'll take a look as time allows and see what I can find.

The message about needing to use a new version of ssacli is a new one to me, and may be worth trying out, just to see if that's causing the variation in output (needs a fix to deal with it either way, but could alleviate your problems in the short-term). Try going out and grabbing the newest version of ssacli (from wherever you're used to getting it from), and see if that helps.

**Comment by mobidyc** [comment]
I updated ssacli to the version 3.25.
and the problem disappeared.

**Comment by cathay4t** [comment]
Great. Do we need to support old ssacli also or just close this issue?

**Comment by tasleson** [comment]
My preference would be do document the minimum supported version of ssacli and close issue.

**Comment by cathay4t** [comment]
@joehandzik Which version of ssacli would you suggested to put in the man page of hpsa plugin?

**Comment by mobidyc** [comment]
I personnaly would prefer that LSM skips an unknown raid card, and continue to the other ones.

In my case ssacli returns an error when I try to access the E208i-a, but as I use only the P408i-p, in command line, there is no issue.

+ I think it will be more difficult to adjust the minimum ssacli version needed each time there is a new controller.

**Comment by cathay4t** [comment]
Silently skip unknown hpsa might waste more time of user when they actually need that card managed by LSM.

I guess suggest user to upgrade their ssacli in PLUGIN_BUG error message might be better.

**Comment by cathay4t** [comment]
Include suggestion on ssacli tool upgrade when parsing error in commit https://github.com/libstorage/libstoragemgmt/commit/00e004891fa58c5427e1753d2f16aaff93e60253
