### ISSUE TITLE
Support HP Smart HBAs and HBA Mode on Gen9 controllers

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#37]
Hey guys,

Leaving this here as an FYI, and will probably take this task on myself. Similar to what you describe for issue #33, Gen9 Smart Array controllers also let you configure the storage controller for raw disk access. So whatever the abstraction path ends up being for the MegaRAID tool, we'll need the same thing for the HPSSACLI tool.

**Comment by cathay4t** [comment]
Sure thing.

**Comment by joehandzik** [comment]
I'd say this is functional...been using it for a while. Closing!
