### ISSUE TITLE
Unable to control some slot LEDs

### ISSUE THREAD

**Issue by hjmallon** [libstorage/libstoragemgmt#383]
This was also posted to the mailing list but it seems a bit quiet there (sorry for x-post).

I am trying to use libstoragemgmt (via udisks) to control the ident and fault LEDs on a 12-disk storage device with an LSI 9400 SAS card. Everything works except the disk in slot “15” (slots 0, 2, 9 and 11 are not filled due to layout). For which the SAS address is not found in _ses_info_get_by_sas_addr. The invoked commands seem to return a list of addresses for every slot (even the empty ones) *except* slot 15. Does anyone know why this might happen and/or what can be done to fix it?

**Comment by tasleson** [comment]
Just to clarify, the the storage device has 16 slots, but only 12 are filled and the last slot, 15 is missing?  We may need to build a version with more debug unless @cathay4t has some insight into what might be going on.

**Comment by tasleson** [comment]
@hjmallon Also sorry for not responding on mailing list and thanks for posting here too!

**Comment by hjmallon** [comment]
Yeah we have 4 backplanes, each 4 slots, but some of them are not filled with disks. All the slot LEDs can be accessed except number 15.

**Comment by tasleson** [comment]
@hjmallon I think it would be helpful to know what the contents of `/sys/class/bsg/*` look like on your system and the value of each `/sys/class/bsg/<name>/device/type`.

**Comment by hjmallon** [comment]
```
# ls -1 /sys/class/bsg/
5:0:0:0
8:0:0:0
8:0:1:0
8:0:10:0
8:0:11:0
8:0:12:0
8:0:2:0
8:0:3:0
8:0:4:0
8:0:5:0
8:0:6:0
8:0:7:0
8:0:8:0
8:0:9:0
end_device-8:0
end_device-8:1
end_device-8:10
end_device-8:11
end_device-8:12
end_device-8:2
end_device-8:3
end_device-8:4
end_device-8:5
end_device-8:6
end_device-8:7
end_device-8:8
end_device-8:9
sas_host8
```

```
# for i in /sys/class/bsg/*/device/type; do echo "$i"; cat "$i"; done
/sys/class/bsg/5:0:0:0/device/type
0
/sys/class/bsg/8:0:0:0/device/type
0
/sys/class/bsg/8:0:10:0/device/type
0
/sys/class/bsg/8:0:1:0/device/type
0
/sys/class/bsg/8:0:11:0/device/type
0
/sys/class/bsg/8:0:12:0/device/type
13
/sys/class/bsg/8:0:2:0/device/type
0
/sys/class/bsg/8:0:3:0/device/type
0
/sys/class/bsg/8:0:4:0/device/type
0
/sys/class/bsg/8:0:5:0/device/type
0
/sys/class/bsg/8:0:6:0/device/type
0
/sys/class/bsg/8:0:7:0/device/type
0
/sys/class/bsg/8:0:8:0/device/type
0
/sys/class/bsg/8:0:9:0/device/type
0
```

**Comment by hjmallon** [comment]
@tasleson I think I have found the issue. I have edited locally and this seems to fix it for me.

I think it is a misunderstanding of the spec (though if you have the most recent SES-3 spec to hand I would appreciate someone checking. The returned SES buffers look like the following in the spec (in the pre-release version I have).

```
+------+----------------------------------------+
| Byte |                Meaning                 |
+------+----------------------------------------+
| 0    | PAGE CODE                              |
| 1    | blah                                   |
| 2    | PAGE LENGTH (labelled in spec 'n - 3') |
| 3    | PAGE LENGTH contd.                     |
| 4    | blah                                   |
| ...  | blah                                   |
| n    | blah                                   |
+------+----------------------------------------+
```

As you can see the `PAGE LENGTH` is labelled `n - 3`, however that means the the size of the buffer is `n + 1` as the 0 byte is counted, so size of buffer equals `PAGE LENGTH + 4`.

Throughout the libses.c code a pointer `endp` is generated to make sure we don't overrun. This ptr is intended to be the byte after the end of the struct but currently it is the last byte of the struct. Therefore I don't get info for the last disk in the list.

Patch which fixes it for me:

```
# git diff
diff --git a/c_binding/libses.c b/c_binding/libses.c
index d58e4a5..1393732 100644
--- a/c_binding/libses.c
+++ b/c_binding/libses.c
@@ -312,7 +312,7 @@ static void _ses_cfg_parse(uint8_t *cfg_data, uint8_t **dp_hdr_begin,
     *dp_hdr_begin = NULL;
 
     cfg_hdr = (struct _ses_cfg_hdr *)cfg_data;
-    end_p = cfg_data + be16toh(cfg_hdr->len_be) + 3;
+    end_p = cfg_data + be16toh(cfg_hdr->len_be) + 4;
     if (end_p >= cfg_data + _SG_T10_SPC_RECV_DIAG_MAX_LEN)
         /* Facing data boundary */
         return;
@@ -462,7 +462,7 @@ static int16_t _ses_find_sas_addr(const char *sas_addr, uint8_t *add_st_data,
     assert(cfg_data != NULL);
 
     add_st = (struct _ses_add_st *) add_st_data;
-    end_p = add_st_data + be16toh(add_st->len_be) + 3;
+    end_p = add_st_data + be16toh(add_st->len_be) + 4;
 
     tmp_p = &add_st->dp_list_begin;
     while(tmp_p < end_p) {
@@ -526,7 +526,7 @@ static int _ses_raw_status_get(char *err_msg, uint8_t *status_data,
     assert(gen_code_be != NULL);
 
     st_hdr = (struct _ses_st_hdr *) status_data;
-    end_p = status_data + be16toh(st_hdr->len_be) + 3;
+    end_p = status_data + be16toh(st_hdr->len_be) + 4;
     status_p = &st_hdr->st_dp_list +
         element_index * _T10_SES_DEV_SLOT_STATUS_LEN;
 
@@ -611,7 +611,7 @@ static int16_t _ses_eiioe(uint8_t *cfg_data, int16_t element_index)
     assert(cfg_data != NULL);
 
     cfg_hdr = (struct _ses_cfg_hdr *)cfg_data;
-    end_p = cfg_data + be16toh(cfg_hdr->len_be) + 3;
+    end_p = cfg_data + be16toh(cfg_hdr->len_be) + 4;
     if (end_p >= cfg_data + _SG_T10_SPC_RECV_DIAG_MAX_LEN)
         /* Facing data boundary */
         return -1;
```

**Comment by tasleson** [comment]
@hjmallon Thank you for digging into this.  I'll double check the spec I have.  If you could, please submit a PR with this fix.

**Comment by tasleson** [comment]
@hjmallon The version of the documentation I have (SES-3 Revision 14) states

```The PAGE LENGTH field indicates the number of bytes that follow in the page.```  Thus I agree that the total number of bytes should be the `PAGE LENGTH + 4`.  The documentation still mentions `PAGE LENGTH (n - 3)` which does seem incorrect to me.

Good find, thanks!

**Comment by hjmallon** [comment]
It is because they label there buffers 0 - n, which means size == n + 1. So unhelpful....
