### ISSUE TITLE
Unable to connect to a NetApp 9.x cDOT

### ISSUE THREAD

**Issue by angystardust** [libstorage/libstoragemgmt#397]
I was trying to connect to a NetApp cDOT using lsmcli but I have this exeption:
```
lsmcli -u ontap+ssl://admin@mynetapp list --type snapshots -P
Password: 
PLUGIN_BUG(2): Unable to find API: system-get-info (vendor error code= 13005) 
```
I've tried with both an ONTAP NetApp Release 9.0P2 and a Release 9.4P2 but had the same results. It does work on an old ONTAP 7mode.

Wondering if lsm support newer ONTAP releases...

Thanks for your support

**Comment by tasleson** [comment]
NetApp is limited to 7mode which NetApp has removed/deprecated.  At some point we will likely remove the plugin all together from libStorageMgmt as we have lost the ability to test it.

**Comment by angystardust** [comment]
thanks for the super-fast reply, @tasleson but the question is: "is there a way to connect to an ONTAP cDOT"?

**Comment by angystardust** [comment]
sorry for asking it again but it isn't clear to me if LSM only supports NetApp 7mode and there is not any way to connect to a recent ONTAP version

**Comment by tasleson** [comment]
@angystardust No, there is no way to use libStorageMgmt to connect to a cDOT (Clustered data on tap).  I correct my earlier comment too.

**Comment by angystardust** [comment]
:( uh that's a pity...
i'll find another way to manage my NetApp cDOT snapshots in batch mode (probably ansible)
thanks for the replies ;)
