### ISSUE TITLE
libstoragemgmt doesn't compile on Alpine Linux (musl)

### ISSUE THREAD

**Issue by PhoenixMage** [libstorage/libstoragemgmt#401]
Mainly due to only having POSIX stderr_r which I believe is deprecated in favor of stderr_l. I have created a quick and dirty patch to switch to stderr_l and have compiled successfully.

**Comment by tasleson** [comment]
If you can supply a PR which addresses the compile issues in a compatible way, we would gladly incorporate it, thanks!

**Comment by tasleson** [comment]
I believe the issue is related to `strerror_*` family of functions and which one we are using in the library.
```c
#include <string.h>

char *strerror(int errnum);

int strerror_r(int errnum, char *buf, size_t buflen);
                   /* XSI-compliant */

char *strerror_r(int errnum, char *buf, size_t buflen);
                   /* GNU-specific */

char *strerror_l(int errnum, locale_t locale);
```

**Comment by PhoenixMage** [comment]
Sorry it was late, you are correct. I will supply a PR shortly.

**Comment by tasleson** [comment]
According to @PhoenixMage this is working now.
