### ISSUE TITLE
Compiler complains about #include <sys/fcntl.h> on Alpine

### ISSUE THREAD

**Issue by PhoenixMage** [libstorage/libstoragemgmt#403]
In file included from scan-scsi-target.c:24:
/usr/include/sys/fcntl.h:1:2: error: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Werror=cpp]
 #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>

**Comment by tasleson** [comment]
Change merged, thanks!
