### ISSUE TITLE
PLUGIN_BUG Arcconf

### ISSUE THREAD

**Issue by ph0en** [libstorage/libstoragemgmt#410]
Getting error

```
 PLUGIN_BUG(2): cmd: '/usr/Arcconf/arcconf create 1 logicaldrive 1024 1 0 5 0 5 0 4 0 4 noprompt', errno: 3, stdout: 'Controllers found: 1

Cannot use a drive multiple times in one logical device!
Invalid arguments.

 Usage: CREATE <Controller#> LOGICALDRIVE [Options] <Size> <RAID#> <Channel# ID#> [Channel# ID#] ... [noprompt] [nologs]

 Usage: CREATE <Controller#> LOGICALDRIVE RVOLUME <LD#> <LD#> [LD#] ... [noprompt] [nologs]
 Usage: CREATE <Controller#> JBOD <Channel# ID#> [Channel# ID#] ... [noprompt] [nologs]
 Usage: CREATE <Controller#> MAXCACHE [options] <size> <RAID#> <Channel# ID#> [Channel# ID#] ... [noprompt] [nologs]
 Example: CREATE 1 LOGICALDRIVE stripesize 512 1024 0 0 0 0 1 
 Example: CREATE 1 LOGICALDRIVE NAME LD1 1024 1 ARRAY 0 
 Example: CREATE 1 LOGICALDRIVE name LD1 stripesize 16 priority high method quick 1024 5 0 0 0 1 0 2 
 Example: CREATE 1 LOGICALDRIVE RVOLUME 0 
 Example: CREATE 1 JBOD 0 0 0 1 
 Example: CREATE 1 MAXCACHE 1024 0 0 0 0 1 
 ===================================================================================

 Create a new logical device or JBOD or Maxcache.

    Options:         Additional creation specifiers.
       Stripesize <STRIPE>: Optional parameter for specifying a stripe size.
                     STRIPE is specified in kilobytes.
                     16, 32, 64, 128, 256*, 512 and 1024 are supported.
       Legs <LEG>:   Optional parameter for specifying number of sub-logical devices.
                     LEG is the number of sub-logical devices for RAID level 50 or 60.
                     RAID 50: 2 - 16 legs, 3 - 32 drives/leg, 128 drives max.
                     RAID 60: 2 - 16 legs, 4 - 16 drives/leg, 128 drives max.
       Name <NAME>:  Optional parameter for specifying the name of the logical
                     device. Valid for Maxcache.
       Priority <PRIORITY>: Initialization Priority for logical drive creation.
                     Valid options are: HIGH*, MED, or LOW. Valid for Maxcache.
       Method <METHOD>: Initialization method for the logical device.Valid for Maxcache.
                     Valid options include: BUILD, CLEAR, QUICK, and
                     DEFAULT.  SKIP skips initialization (for recovery only).
       Rcache <RCACHE>: Read Cache setting for the logical device.
                     Valid options are: RON and ROFF
       Wcache <WCACHE>: Write Cache setting for the logical device.
                     Valid options are: WT, WB, and WBB
                     WT:  write-through (Disabled)
                     WB:  write-back (Enabled)
                     WBB: write-back (Enabled) when protected by battery/ZMM

       MaxCacheReadCache <MAXCACHE>: MaxCache Read Cache setting for the logical device.
                     Valid options are: ION and IOFF

       MaxCache Write Cache Commands: Please contact your Adaptec representative to enable the SSD write caching feature
       MaxCacheWriteCache <MAXCACHE>: MaxCache Write Cache setting for the logical device.
                     Valid options are: ION and IOFF
       MaxCacheWritePolicy <POLICY>: MaxCache Write Cache Policy setting for the logical device.
                     This argument is valid only if MaxCacheWriteCache is ION
                     Valid options are: WB,WT,INSTWB and WBWITHWT
    Size:            Size of the logical device in megabytes. Valid for Maxcache.
                     Use MAX to set size to all remaining available space.
                     Use MAXMBR to set the size to 2TB.
    Raid#:           Raid level for the new logical device.
                     0, 1, 1E, 10, 5, 5EE, 50, 6, 60, and volume are supported.
                     The supported raid levels for Maxcache are simple volume,0,1,1E,5.
    RVOLUME          Raid Level for a raid volume logical device.
    LD#              Logical device numbers for the 2 or more distinct logical devices
                     to be concatenated into the raid volume.
                     RAID levels 0, 1, and 5 are supported RVOLUME members.
                     All RVOLUME members must be the same RAID level.
    Channel# ID#:    A list of space-delimited channel number and
                     device number pairs for each device to add
                     to the logical device.

    MAXCACHE     :   Command to create Maxcache container.Only SSDs can be used to create Maxcache.

       noprompt:     Don't prompt for confirmation.

     * default parameter in MOST circumstances', stderr: '' 

```
while using sample code [Create Volume RAID](https://libstorage.github.io/libstoragemgmt-doc/doc/py_api_user_guide.html#611-create-raid-volume--lsmclientvolume_raid_create) with my edit 
`ssd_disks = [d for d in disks if d.name.split()[0] == 'Samsung']`
Also having the same error while trying to use cli
`lsmcli volume-raid-create --uri 'arcconf://' --name 'cli_test_raid' --raid-type RAID1 --disk S4BFNG0KA16159J --disk S3YKNX0M120554J`

Looks like the plugin duplicates info about disks `0 5 0 5 0 4 0 4` during string build

### Steps to reproduce:

1. Load centos live
2. `yum install -y libstoragemgmt-python libstoragemgmt-arcconf-plugin
wget http://download.adaptec.com/raid/storage_manager/arcconf_v2_04_22665.zip
unzip arcconf_v2_04_22665.zip
yum install -y linux_x64/rpm/Arcconf-2.04-22665.x86_64.rpm
setenforce 0`
3. Run code from the sample or cli command

**Comment by tasleson** [comment]
Just got back from holiday, will investigate.

**Comment by tasleson** [comment]
@sharath-t Would you have some time to take a look at this?  I'm looking for hardware to give this a try.

**Comment by sharath-t** [comment]
Hi @tasleson, Thanks for the mention, i somehow missed the issue email. I will look into this.

meanwhile, @ph0en , may i know which version of lsmcli you are using? The reason is, there has been lot of enhancement to arcconf plugin in [1.8.0](https://github.com/libstorage/libstoragemgmt/releases/tag/1.8.0) . request you to try with 1.8.0+ version if you have not already.

Regards,
Sharath TS

**Comment by sharath-t** [comment]
@ph0en 
the command is creating volume as required in my set up. attaching screenshot for you reference.

![image](https://user-images.githubusercontent.com/45253441/74125209-a166d680-4bfa-11ea-9ff5-352ab18dd07e.png)


However, on completion of command, the output is not that is expected " PLUGIN_BUG(2): volume_raid_create(): Got unexpected count(not 1) of new volumes: [] " This is due to error in arcconf plugin where it is trying to fetch pool ID with incorrect ID. i will place a PR for this fix soon.

**Comment by ph0en** [comment]
@sharath-t  libstoragemgmt-arcconf-plugin version is 1.7.3-3.el7 from CentOS 7 base repo.
Getting error on Adaptec 6805T now. Don't sure what controller version was during last error.
Where can I download 1.8.0+ rpm?

**Comment by sharath-t** [comment]
Hello @ph0en , Thanks for confirming the version. 

i am not sure if rpm is available for 1.8.0+ @tasleson ? 

you may have to build from the source code. use https://github.com/libstorage/libstoragemgmt/archive/master.zip link to get latest source code.

**Comment by tasleson** [comment]
@ph0en @sharath-t CentOS 7 release are from RHEL7 which at this point I don't think we'll be picking this up ...  I'll create some rpm's and make them available for you to address this issue.

**Comment by tasleson** [comment]
@ph0en I built some packages for CentOS 7 using the latest release.  Hope this helps: https://fedorapeople.org/~tasleson/lsm/centos7/
