### ISSUE TITLE
Remove libxml2 dependency

### ISSUE THREAD

**Issue by tasleson** [libstorage/libstoragemgmt#498]
The library is using libxml for URI parsing and query strings parameters.  It should be fairly easy to remove this by implementing it internally, thus removing this entire dependency.

**Comment by tasleson** [comment]
resolved with https://github.com/libstorage/libstoragemgmt/pull/502

**Comment by lkx007** [comment]
您好，您的来信已收到，我将会尽快给您回复，谢谢~~
