### ISSUE TITLE
Install docs for Rhel7 don't actually cover all required packages

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#55]
Just an FYI for anyone who has time to get around to cleaning up the documentation here: http://libstorage.github.io/libstoragemgmt-doc/doc/install.html

It didn't cover a couple of steps I needed to execute:

yum install libmicrohttpd*
yum install json-c*

**Comment by cathay4t** [comment]
@joehandzik I don't get what you mean.

That page already has these lines for RHEL/Fedora:
```

# If you want the REST API daemon
$ sudo yum install libmicrohttpd-devel json-c-devel
```
and many others for opensuse and debian.

**Comment by joehandzik** [comment]
Yeah, I realized that a little while ago...I still don't think that's the best way to deal with this though. The instructions as they're worded are perhaps acceptable for someone installing as a package, but for development it's not really an "option". How about we work on an "install_deps.sh" script instead? Take some of the guesswork out of it? See: https://github.com/ceph/ceph/blob/master/install-deps.sh for an example.

**Comment by cathay4t** [comment]
For developer, how about this page:
http://libstorage.github.io/libstoragemgmt-doc/doc/lib_dev_guide.html#1-setup-developer-environment

IMHO, `install_deps.sh` might requires extra un-needed care on different linux releases.
I prefer leting user follow the document to install required packages than asking user to
run a complex script with root permission.

**Comment by joehandzik** [comment]
Ok, just a suggestion. I do see that you've got a developer-specific set of install guides, which I can live with.
