### ISSUE TITLE
lsm email addresses are next to the wrong hotlink

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#62]
Currently, on http://libstorage.github.io/libstoragemgmt-doc/

Developer Mailing list: libstoragemgmt-users@lists.fedorahosted.org
User Mailing List: libstoragemgmt-devel@lists.fedorahosted.org

Should be:

Developer Mailing list: libstoragemgmt-devel@lists.fedorahosted.org
User Mailing List: libstoragemgmt-users@lists.fedorahosted.org

But hey, now I'm just signed up for both mailing lists. :)

**Comment by tasleson** [comment]
Corrected with https://github.com/libstorage/libstoragemgmt-doc/commit/16a06b94e05cf55b050d2b58ddcbe24f22383be6

Thanks @joehandzik
