### ISSUE TITLE
Python 2.7.10 miss behaive on `add_subparsers`

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#78]
The seperater defined in `lsmenv sim lsmcli -t, list --type systems` does not work.

Might be python regression.

This cause cmdtest silently skiped.

**Comment by cathay4t** [comment]
This is caused by https://bugs.python.org/issue23058 introduced by python 2.7.9.
As that was closed as 'not a bug', we should considering a workaround for this.

**Comment by tasleson** [comment]
Based on the comments it appears we are just depending on a bug that was fixed.  So looking at this commit is suppose to be educational: https://github.com/nickstenning/honcho/commit/1319da72f2ae0dc14d6f0631ce654007691cd839

**Comment by cathay4t** [comment]
Closing this issue. Fixed in PR #76
