### ISSUE TITLE
Add depenency file

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#79]
Files user could use to install depenency:
```
# For RHEL/Centos/Fedora
sudo yum install `cat rh_rpm_depenency`
# For Debian/Ubuntu
sudo apt-get install `cat deb_depenency`
# For suse
sudo zypper in `cat suse_rpm_depenecy`.
```

**Comment by joehandzik** [comment]
I'm voting we take care of this in 1.4. :)

**Comment by cathay4t** [comment]
:+1:  for postponing to 1.4

**Comment by cathay4t** [comment]
Change to 1.3 to make my document life easier.

**Comment by cathay4t** [comment]
Closing as PR #137 fixed this.

**Comment by joehandzik** [comment]
@cathay4t I was just trying to save work if we didn't have time to get it in, glad you had time!
