### ISSUE TITLE
Functionality still needed

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#81]
Hey guys,

Feel free to let me know if there's a different place you'd prefer to have me put this content. Thank you very much to @cathay4t for his work in helping me fix my own PRs and refactoring some of my requested functionality to better fit into lsm. The following is the rest of what I'd like to see added in the short term to lsm to suit what I'm driving towards across a few different storage solutions (Ceph being the primary target). 

1. Disk location (existing PR, #63) - Something very easy to expose via hpssacli and sysfs, gives customers a much easier way to figure out where their drive is.
2. SCSI generic path for disks and volumes - I have existing commits in a personal branch for this, but it leverages lsscsi. If there's a udev mechanism in the vein of what you already developed for the sd path, I think that'd be a fine implementation. This is desirable to continue to eliminate external tool requirements (helps make lsm that much more of a single source of data).
3. Disk SAS address - Currently collecting via 'lsscsi -tg', but I have also added a sysfs attribute into more recent hpsa driver releases that contain this information.
4. SEP SCSI generic path - This is where things get trickier. I need this for the next line item. I currently grab each disk's SEP under the covers via some combination of lsscsi and sg_ses. I'm open to alternative implementations.
5. Disk LED enable/disable - This was more or less the initial feature I targeted to add into Ceph. To accomplish this, I need a unique disk identifier (Disk SAS address from item 3), the SEP's sg path (item 4), and the ability to call into sg_ses. I haven't really looked to see if there's a library call I could make instead, but I'm not aware of a more...programmatic way to accomplish this, hence the sg_ses call.

As always, I'm open to different ideas about how to implement all of this. My primary goal was to avoid reinventing the wheel, which is why you see a lot of calls into lsscsi or sg_ses scattered across all of these. Feel free to look at my branch (here: https://github.com/HP-Scale-out-Storage/libstoragemgmt/tree/wip-all) or ask me questions if what I'm requesting doesn't make sense. I'm open to refactoring any and all of the commits in my wip-all branch, but I'm expecting you guys to prefer to reimplement some too.

**Comment by cathay4t** [comment]
@joehandzik Thank you. I will look into these. 

1. Easy job, I will allow plugin provide this info and check whether we create library level method also
    for SES disks.

2. I will create a library function like `sg_path_of_sd_path("/dev/sdb")`. But why we need it instead of 5). 

3. Need to read some T10 SPEC to find more generic way for retrieving SAS address of both SES and non-SES disks.

4. Could you list some user case about using SES /dev/sgX of certain /dev/sda when below solution created?

5. How about LSM library function `lsm_scsi_disk_ident_led_set("/dev/sdX")` and `lsm_scsi_disk_ident_led_clear("/dev/sdX")`?  LSM code could do the complex SES works or even better to support IBPI SGPIO.

**Comment by joehandzik** [comment]
1. Awesome! Would my current PR about that functionality be an acceptable starting point?

2. Seems like a good enough method. Use cases I can think of: as the target of a drive firmware flash and to retrieve SMART data from a physical disk. Beyond the use cases, some customers just like to be able to see that data for their own metadata and topology tracking purposes (again, think about what lsscsi is capable of showing). I don't see downsides to exposing that path through lsm.

3. Fair enough. My priority is SES-compliant environments, and more specifically the higher-end HBA/RAID cards on the market. it's tough to cover every HBA or chipset out there, hence the way lsm is designed to begin with (feature flags for individual supported storage hardware).

4. Similar to line item 2, there's a set of functionality that just doesn't exist in lsm (yet) that a user may want access to, and providing the SEP's scsi generic path would make it really simple for a user to access that functionality. An example I'm mulling over is spinning down individual drives behind an HBA. It's not something every customer needs, but for colder storage environments (which, say, Ceph could be the solution of choice for) I have customers today that do it. 

5. Yeah, that sounds fine. I very much advocate lsm doing the complex SES work behind the scenes for library functions that we add here. The goal should absolutely make it so that users don't have much need for targeting the SEP's scsi generic path themselves...but that'll be a work in progress for at least a year IMO.

**Comment by cathay4t** [comment]
OK. I will look into your PR #65 and work on `lsm_scsi_disk_ident_led_set()`.
After that we back to this topic about sg again.

**Comment by joehandzik** [comment]
@cathay4t I'm going to close this out. I think you've covered the minimum for what I need, though I would like to yank the disk sas addresses and scsi generic paths out at some point. Thanks!

**Comment by cathay4t** [comment]
No problem. If you got user case needs sas address or /dev/sgX, let us know.
