### ISSUE TITLE
libstoragemgmt fails when a system does not have a serial number

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#90]
We at HPE intend to fix this, but I'm documenting here so I don't forget. We've been running some tests on a variety of configurations, and for our B140i Dynamic Smart Array mode (our SW RAID implementation), apparently libstoragemgmt errors out rather than just skipping over the system. 

Is there a preferred method of handling this? My thought (as I alluded to) is to just skip the system entirely. We could also make up a serial number, though that could have unintended consequences.

**Comment by tasleson** [comment]
I would suggest taking anything that is unique and relatively stable for the system and take the md5 of it and use it in place of the missing serial number, perhaps the name?

**Comment by joehandzik** [comment]
Not a bad idea, we'll look into that. The good news here is that there will never be two "B140i" controllers in a single system, so your implementation suggestion seems to work for current architectures.

**Comment by cathay4t** [comment]
@joehandzik Could you send me the output of `hpssacli ctrl all show config detail` on "B140i"?
I might be able to craft some workaround on issue.

**Comment by joehandzik** [comment]
Hey @cathay4t, sorry for the delay, long weekend here. I think we have a solution (we're going to use the chassis serial number for the B140i, an md5 of the name wouldn't work uniquely to distinguish boot controller in a cluster environment), but if we run into trouble I'll post the output here and have you take a look. I expect a PR in the next couple of days. Thanks!

**Comment by joehandzik** [comment]
Update: I have a fix that has worked around this issue and another similar issue with the B1x0i series on our side. I'm OoO today, but I'll generate a PR tomorrow.

**Comment by joehandzik** [comment]
Fixed in PR #94, close this when you accept the PR. Thanks!
