### ISSUE TITLE
[RFC] Library level function for ident and fault LED

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#91]
Initial design:
* ~~~C: `int lsm_scsi_ident_led_set(const char disk_path, lsm_error *lsm_err)`~~~
* C: `int lsm_local_disk_ident_led_set(const char disk_path, lsm_error *lsm_err)`
* ~~~Python: `lsm.SCSI.ident_led_set(disk_path)`~~~
* Python: `lsm.LocalDisk.ident_led_set(disk_path)`
* And others for fault led and clear functions.

Workflow:
* Use SGIO in C. (Python API just a wrap via lsm._scsi_clib)
* Find out the target port SAS address of sdX via VPD 0x83 page.
* Enumerate all SES sgX to find out which sgX is manageing this SAS address.
* Find out the slot index.
* Use SES-4 '6.1.3 Enclosure Control diagnostic page' to `RQST IDENT`.
* Check return data about whether ident/fault is supported.
* If SES is not supported, try other technology used by [ledmon][1]

[1]: https://sourceforge.net/projects/ledmon/

**Comment by joehandzik** [comment]
This sounds good, @cathay4t, it mirrors the flow I have in my fork and drops the requirements I injected for lsscsi and sg_ses. I'm glad you knew about SGIO, seems like the best option for what I've requested. Thank you for all your work here!

**Comment by joehandzik** [comment]
One concern I do have though is with Intel AHCI/SATA controllers. They support IBPI. Will we be able to someday support those devices with generic inquiries too? I suppose the right way to do that would be to create a "IBPI://" plugin, eh? It's not a priority for me, but I'm sure some users would appreciate it.

**Comment by cathay4t** [comment]
@joehandzik I intend to change function name to `lsm_block_xxx` which indicate we will ATA or NVMe in the future in PR #92 
Yes. We could support IBPI in the future. But instead of creating new plugin, I would like to extend the
`lsm_block_ident_led_set` to support IBPI, let the library auto choose SES or IBPI or others tech used by
intel project [ledmon][1].

[1]: https://sourceforge.net/projects/ledmon/

**Comment by cathay4t** [comment]
Closing this issue.
Please continue the discussion in PR #105.
