### ISSUE TITLE
Should not raise 'no deamon' error when checking help message of lsmcli.

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#97]
```
[fge@Gris-Laptop libstoragemgmt-code]$  lsmenv sim lsmcli  vc --help
Device alias: sim
URI: sim://
lsmcli vc --help
PLUGIN_IPC_FAIL(301): Unable to connect to lsmd, daemon started? 
Command exited with non-zero status 4
```

**Comment by tasleson** [comment]
I looked at this one today and this one is interesting.  If you place the `--help` before the alias it works as expected.  For some currently unknown reason when `--help` is after the alias we return from `parse_known_args` with unknown args containing `--help`.  When we later try to call  `self.args.func(self.args)` we call into `handle_alias` which in turn calls `parse_args` again which catches that we have `--help` specified.  This of course only happens after we have established a connection with the daemon so we fail with the daemon present when really all we wanted was to display the help text.

Additionally, with this bug we are allowing random junk on the command line as long as it doesn't utilize an alias, eg. 

```
lsmcli list --type systems  --uri sim:// --we --don\'t --error --on --this --but --we --should
ID     | Name                          | Status | Info | FW Ver                                                  | Mode    | Read Cache Percentage
--------------------------------------------------------------------------------------------------------------------------------------------------
sim-01 | LSM simulated storage plug-in | OK     |      | LSM_SIMULATOR_DATA_3.9_47588d4b158a37889ddf44eeb8e88b0f | HW RAID | 10
```

I fear that we are abusing the argparse library excessively, to add features that it doesn't natively support which is causing us pain with issues like this one and when trying to migrate to py3.
